FROM tlcpack/ci-gpu:v0.87

# COPY /ubuntu1804_install_llvm.sh /install/ubuntu1804_install_llvm.sh
# RUN bash /install/1804ubuntu_install_llvm.sh

COPY utils/apt-install-and-clear.sh /usr/local/bin/apt-install-and-clear

# Build TVM
COPY /install_tvm_gpu_v0.7.0.sh /install/install_tvm_gpu_v0.7.0.sh
RUN bash /install/install_tvm_gpu_v0.7.0.sh

# Environment variables
ENV PYTHONPATH=/usr/tvm/python:/usr/tvm/vta/python:${PYTHONPATH}
ENV TVM_HOME=/usr/tvm
ENV PATH=/usr/local/nvidia/bin:${PATH}
ENV PATH=/usr/local/cuda/bin:${PATH}
ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/nvidia/lib64:${LD_LIBRARY_PATH}